# Generated by Django 5.2.1 on 2025-06-04 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(choices=[('hearts', 'hearts'), ('diamonds', 'diamonds'), ('clubs', 'clubs'), ('spades', 'spades')])),
                ('rank', models.CharField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), ('J', 'J'), ('Q', 'Q'), ('K', 'K'), ('A', 'A')])),
                ('is_face_up', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('suit', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solitaire.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_card', to='solitaire.deck')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('deck', 'position')},
            },
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(related_name='deck', through='solitaire.DeckCard', to='solitaire.card'),
        ),
    ]
