# Generated by Django 5.2.1 on 2025-06-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solitaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deckcard',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='card',
            name='rank',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('J', 'J'), ('Q', 'Q'), ('K', 'K'), ('A', 'A')]),
        ),
        migrations.AlterField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(through='solitaire.DeckCard', to='solitaire.card'),
        ),
    ]
